#!/bin/bash -el

# do not remove, circus is needed to manage application processes
# and its environment variables
echo "deb http://archive.ubuntu.com quantal-backports main" >> /etc/apt/sources.list
cat /etc/apt/sources.list
apt-get update
apt-get install git openssh-server python-pip libzmq-dev g++ python-dev wget jq -y
pip install git+https://github.com/andrewsmedina/circus.git@validate_option_hooks
pip install -e git+https://github.com/g00d-guy/tsuru-circus#egg=tsuru-circus
mkdir /var/run/sshd
echo "export DEBIAN_FRONTEND=noninteractive" >> /etc/profile
