#!/bin/bash -el

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/config

mkdir -p /etc/circus
cp ${SOURCE_DIR}/utils/circus.ini /etc/circus/circus.ini
#mkdir /app
useradd -m ${USER} -s /bin/bash
#chown ${USER}:${USER} /app
echo "ubuntu ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
